const nationlities = {
  'AFG;Afghan;': {
    code: 'AFG',
    smallCode: 'AF',
    country: 'Afghanistan',
    nationality: 'Afghan',
  },
  'ALA;Land Island;': {
    code: 'ALA',
    smallCode: 'AX',
    country: 'Land Islands',
    nationality: 'Land Island',
  },
  'ALB;Albanian;': {
    code: 'ALB',
    smallCode: 'AL',
    country: 'Albania',
    nationality: 'Albanian',
  },
  'DZA;Algerian;': {
    code: 'DZA',
    smallCode: 'DZ',
    country: 'Algeria',
    nationality: 'Algerian',
  },
  'ASM;American Samoan;': {
    code: 'ASM',
    smallCode: 'AS',
    country: 'American Samoa',
    nationality: 'American Samoan',
  },
  'AND;Andorran;': {
    code: 'AND',
    smallCode: 'AD',
    country: 'Andorra',
    nationality: 'Andorran',
  },
  'AGO;Angolan;': {
    code: 'AGO',
    smallCode: 'AO',
    country: 'Angola',
    nationality: 'Angolan',
  },
  'AIA;Anguillan;': {
    code: 'AIA',
    smallCode: 'AI',
    country: 'Anguilla',
    nationality: 'Anguillan',
  },
  'ATA;Antarctic;': {
    code: 'ATA',
    smallCode: 'AQ',
    country: 'Antarctica',
    nationality: 'Antarctic',
  },
  'ATG;Antiguan or Barbudan;': {
    code: 'ATG',
    smallCode: 'AG',
    country: 'Antigua and Barbuda',
    nationality: 'Antiguan or Barbudan',
  },
  'ARG;Argentine;': {
    code: 'ARG',
    smallCode: 'AR',
    country: 'Argentina',
    nationality: 'Argentine',
  },
  'ARM;Armenian;': {
    code: 'ARM',
    smallCode: 'AM',
    country: 'Armenia',
    nationality: 'Armenian',
  },
  'ABW;Aruban;': {
    code: 'ABW',
    smallCode: 'AW',
    country: 'Aruba',
    nationality: 'Aruban',
  },
  'AUS;Australian;': {
    code: 'AUS',
    smallCode: 'AU',
    country: 'Australia',
    nationality: 'Australian',
  },
  'AUT;Austrian;': {
    code: 'AUT',
    smallCode: 'AT',
    country: 'Austria',
    nationality: 'Austrian',
  },
  'AZE;Azerbaijani;': {
    code: 'AZE',
    smallCode: 'AZ',
    country: 'Azerbaijan',
    nationality: 'Azerbaijani',
  },
  'BHS;Bahamian;': {
    code: 'BHS',
    smallCode: 'BS',
    country: 'Bahamas',
    nationality: 'Bahamian',
  },
  'BHR;Bahraini;': {
    code: 'BHR',
    smallCode: 'BH',
    country: 'Bahrain',
    nationality: 'Bahraini',
  },
  'BGD;Bangladeshi;': {
    code: 'BGD',
    smallCode: 'BD',
    country: 'Bangladesh',
    nationality: 'Bangladeshi',
  },
  'BRB;Barbadian;': {
    code: 'BRB',
    smallCode: 'BB',
    country: 'Barbados',
    nationality: 'Barbadian',
  },
  'BLR;Belarusian;': {
    code: 'BLR',
    smallCode: 'BY',
    country: 'Belarus',
    nationality: 'Belarusian',
  },
  'BEL;Belgian;': {
    code: 'BEL',
    smallCode: 'BE',
    country: 'Belgium',
    nationality: 'Belgian',
  },
  'BLZ;Belizean;': {
    code: 'BLZ',
    smallCode: 'BZ',
    country: 'Belize',
    nationality: 'Belizean',
  },
  'BEN;Beninese;': {
    code: 'BEN',
    smallCode: 'BJ',
    country: 'Benin',
    nationality: 'Beninese',
  },
  'BMU;Bermudian;': {
    code: 'BMU',
    smallCode: 'BM',
    country: 'Bermuda',
    nationality: 'Bermudian',
  },
  'BTN;Bhutanese;': {
    code: 'BTN',
    smallCode: 'BT',
    country: 'Bhutan',
    nationality: 'Bhutanese',
  },
  'BOL;Bolivian;': {
    code: 'BOL',
    smallCode: 'BO',
    country: 'Bolivia (Plurinational State of)',
    nationality: 'Bolivian',
  },
  'BES;Bonaire;': {
    code: 'BES',
    smallCode: 'BQ',
    country: 'Bonaire',
    nationality: 'Bonaire',
  },
  'BIH;Bosnian or Herzegovinian;': {
    code: 'BIH',
    smallCode: 'BA',
    country: 'Bosnia and Herzegovina',
    nationality: 'Bosnian or Herzegovinian',
  },
  'BWA;Motswana;': {
    code: 'BWA',
    smallCode: 'BW',
    country: 'Botswana',
    nationality: 'Motswana',
  },
  'BVT;Bouvet Island;': {
    code: 'BVT',
    smallCode: 'BV',
    country: 'Bouvet Island',
    nationality: 'Bouvet Island',
  },
  'BRA;Brazilian;': {
    code: 'BRA',
    smallCode: 'BR',
    country: 'Brazil',
    nationality: 'Brazilian',
  },
  'IOT;BIOT;': {
    code: 'IOT',
    smallCode: 'IO',
    country: 'British Indian Ocean Territory',
    nationality: 'BIOT',
  },
  'BRN;Bruneian;': {
    code: 'BRN',
    smallCode: 'BN',
    country: 'Brunei Darussalam',
    nationality: 'Bruneian',
  },
  'BGR;Bulgarian;': {
    code: 'BGR',
    smallCode: 'BG',
    country: 'Bulgaria',
    nationality: 'Bulgarian',
  },
  'BFA;Burkinab\u00e9;': {
    code: 'BFA',
    smallCode: 'BF',
    country: 'Burkina Faso',
    nationality: 'Burkinab\u00e9',
  },
  'BDI;Burundian;': {
    code: 'BDI',
    smallCode: 'BI',
    country: 'Burundi',
    nationality: 'Burundian',
  },
  'CPV;Cabo Verdean;': {
    code: 'CPV',
    smallCode: 'CV',
    country: 'Cabo Verde',
    nationality: 'Cabo Verdean',
  },
  'KHM;Cambodian;': {
    code: 'KHM',
    smallCode: 'KH',
    country: 'Cambodia',
    nationality: 'Cambodian',
  },
  'CMR;Cameroonian;': {
    code: 'CMR',
    smallCode: 'CM',
    country: 'Cameroon',
    nationality: 'Cameroonian',
  },
  'CAN;Canadian;': {
    code: 'CAN',
    smallCode: 'CA',
    country: 'Canada',
    nationality: 'Canadian',
  },
  'CYM;Caymanian;': {
    code: 'CYM',
    smallCode: 'KY',
    country: 'Cayman Islands',
    nationality: 'Caymanian',
  },
  'CAF;Central African;': {
    code: 'CAF',
    smallCode: 'CF',
    country: 'Central African Republic',
    nationality: 'Central African',
  },
  'TCD;Chadian;': {
    code: 'TCD',
    smallCode: 'TD',
    country: 'Chad',
    nationality: 'Chadian',
  },
  'CHL;Chilean;': {
    code: 'CHL',
    smallCode: 'CL',
    country: 'Chile',
    nationality: 'Chilean',
  },
  'CHN;Chinese;': {
    code: 'CHN',
    smallCode: 'CN',
    country: 'China',
    nationality: 'Chinese',
  },
  'CXR;Christmas Island;': {
    code: 'CXR',
    smallCode: 'CX',
    country: 'Christmas Island',
    nationality: 'Christmas Island',
  },
  'CCK;Cocos Island;': {
    code: 'CCK',
    smallCode: 'CC',
    country: 'Cocos (Keeling) Islands',
    nationality: 'Cocos Island',
  },
  'COL;Colombian;': {
    code: 'COL',
    smallCode: 'CO',
    country: 'Colombia',
    nationality: 'Colombian',
  },
  'COM;Comoran;': {
    code: 'COM',
    smallCode: 'KM',
    country: 'Comoros',
    nationality: 'Comoran',
  },
  'COG;Congolese;': {
    code: 'COG',
    smallCode: 'CG',
    country: 'Congo (Republic of the)',
    nationality: 'Congolese',
  },
  'COD;Congolese;': {
    code: 'COD',
    smallCode: 'CD',
    country: 'Congo (Democratic Republic of the)',
    nationality: 'Congolese',
  },
  'COK;Cook Island;': {
    code: 'COK',
    smallCode: 'CK',
    country: 'Cook Islands',
    nationality: 'Cook Island',
  },
  'CRI;Costa Rican;': {
    code: 'CRI',
    smallCode: 'CR',
    country: 'Costa Rica',
    nationality: 'Costa Rican',
  },
  'CIV;Ivorian;': {
    code: 'CIV',
    smallCode: 'CI',
    country: "C\u00f4te d'Ivoire",
    nationality: 'Ivorian',
  },
  'HRV;Croatian;': {
    code: 'HRV',
    smallCode: 'HR',
    country: 'Croatia',
    nationality: 'Croatian',
  },
  'CUB;Cuban;': {
    code: 'CUB',
    smallCode: 'CU',
    country: 'Cuba',
    nationality: 'Cuban',
  },
  'CUW;Cura\u00e7aoan;': {
    code: 'CUW',
    smallCode: 'CW',
    country: 'Cura\u00e7ao',
    nationality: 'Cura\u00e7aoan',
  },
  'CYP;Cypriot;': {
    code: 'CYP',
    smallCode: 'CY',
    country: 'Cyprus',
    nationality: 'Cypriot',
  },
  'CZE;Czech;': {
    code: 'CZE',
    smallCode: 'CZ',
    country: 'Czech Republic',
    nationality: 'Czech',
  },
  'DNK;Danish;': {
    code: 'DNK',
    smallCode: 'DK',
    country: 'Denmark',
    nationality: 'Danish',
  },
  'DJI;Djiboutian;': {
    code: 'DJI',
    smallCode: 'DJ',
    country: 'Djibouti',
    nationality: 'Djiboutian',
  },
  'DMA;Dominican;': {
    code: 'DMA',
    smallCode: 'DM',
    country: 'Dominica',
    nationality: 'Dominican',
  },
  'DOM;Dominican;': {
    code: 'DOM',
    smallCode: 'DO',
    country: 'Dominican Republic',
    nationality: 'Dominican',
  },
  'ECU;Ecuadorian;': {
    code: 'ECU',
    smallCode: 'EC',
    country: 'Ecuador',
    nationality: 'Ecuadorian',
  },
  'EGY;Egyptian;': {
    code: 'EGY',
    smallCode: 'EG',
    country: 'Egypt',
    nationality: 'Egyptian',
  },
  'SLV;Salvadoran;': {
    code: 'SLV',
    smallCode: 'SV',
    country: 'El Salvador',
    nationality: 'Salvadoran',
  },
  'GNQ;Equatorial Guinean;': {
    code: 'GNQ',
    smallCode: 'GQ',
    country: 'Equatorial Guinea',
    nationality: 'Equatorial Guinean',
  },
  'ERI;Eritrean;': {
    code: 'ERI',
    smallCode: 'ER',
    country: 'Eritrea',
    nationality: 'Eritrean',
  },
  'EST;Estonian;': {
    code: 'EST',
    smallCode: 'EE',
    country: 'Estonia',
    nationality: 'Estonian',
  },
  'ETH;Ethiopian;': {
    code: 'ETH',
    smallCode: 'ET',
    country: 'Ethiopia',
    nationality: 'Ethiopian',
  },
  'FLK;Falkland Island;': {
    code: 'FLK',
    smallCode: 'FK',
    country: 'Falkland Islands (Malvinas)',
    nationality: 'Falkland Island',
  },
  'FRO;Faroese;': {
    code: 'FRO',
    smallCode: 'FO',
    country: 'Faroe Islands',
    nationality: 'Faroese',
  },
  'FJI;Fijian;': {
    code: 'FJI',
    smallCode: 'FJ',
    country: 'Fiji',
    nationality: 'Fijian',
  },
  'FIN;Finnish;': {
    code: 'FIN',
    smallCode: 'FI',
    country: 'Finland',
    nationality: 'Finnish',
  },
  'FRA;French;': {
    code: 'FRA',
    smallCode: 'FR',
    country: 'France',
    nationality: 'French',
  },
  'GUF;French Guianese;': {
    code: 'GUF',
    smallCode: 'GF',
    country: 'French Guiana',
    nationality: 'French Guianese',
  },
  'PYF;French Polynesian;': {
    code: 'PYF',
    smallCode: 'PF',
    country: 'French Polynesia',
    nationality: 'French Polynesian',
  },
  'ATF;French Southern Territories;': {
    code: 'ATF',
    smallCode: 'TF',
    country: 'French Southern Territories',
    nationality: 'French Southern Territories',
  },
  'GAB;Gabonese;': {
    code: 'GAB',
    smallCode: 'GA',
    country: 'Gabon',
    nationality: 'Gabonese',
  },
  'GMB;Gambian;': {
    code: 'GMB',
    smallCode: 'GM',
    country: 'Gambia',
    nationality: 'Gambian',
  },
  'GEO;Georgian;': {
    code: 'GEO',
    smallCode: 'GE',
    country: 'Georgia',
    nationality: 'Georgian',
  },
  'DEU;German;': {
    code: 'DEU',
    smallCode: 'DE',
    country: 'Germany',
    nationality: 'German',
  },
  'GHA;Ghanaian;': {
    code: 'GHA',
    smallCode: 'GH',
    country: 'Ghana',
    nationality: 'Ghanaian',
  },
  'GIB;Gibraltar;': {
    code: 'GIB',
    smallCode: 'GI',
    country: 'Gibraltar',
    nationality: 'Gibraltar',
  },
  'GRC;Greek;': {
    code: 'GRC',
    smallCode: 'GR',
    country: 'Greece',
    nationality: 'Greek',
  },
  'GRL;Greenlandic;': {
    code: 'GRL',
    smallCode: 'GL',
    country: 'Greenland',
    nationality: 'Greenlandic',
  },
  'GRD;Grenadian;': {
    code: 'GRD',
    smallCode: 'GD',
    country: 'Grenada',
    nationality: 'Grenadian',
  },
  'GLP;Guadeloupe;': {
    code: 'GLP',
    smallCode: 'GP',
    country: 'Guadeloupe',
    nationality: 'Guadeloupe',
  },
  'GUM;Guamanian;': {
    code: 'GUM',
    smallCode: 'GU',
    country: 'Guam',
    nationality: 'Guamanian',
  },
  'GTM;Guatemalan;': {
    code: 'GTM',
    smallCode: 'GT',
    country: 'Guatemala',
    nationality: 'Guatemalan',
  },
  'GGY;Channel Island;': {
    code: 'GGY',
    smallCode: 'GG',
    country: 'Guernsey',
    nationality: 'Channel Island',
  },
  'GIN;Guinean;': {
    code: 'GIN',
    smallCode: 'GN',
    country: 'Guinea',
    nationality: 'Guinean',
  },
  'GNB;Bissau-Guinean;': {
    code: 'GNB',
    smallCode: 'GW',
    country: 'Guinea-Bissau',
    nationality: 'Bissau-Guinean',
  },
  'GUY;Guyanese;': {
    code: 'GUY',
    smallCode: 'GY',
    country: 'Guyana',
    nationality: 'Guyanese',
  },
  'HTI;Haitian;': {
    code: 'HTI',
    smallCode: 'HT',
    country: 'Haiti',
    nationality: 'Haitian',
  },
  'HMD;Heard Island or McDonald Islands;': {
    code: 'HMD',
    smallCode: 'HM',
    country: 'Heard Island and McDonald Islands',
    nationality: 'Heard Island or McDonald Islands',
  },
  'VAT;Vatican;': {
    code: 'VAT',
    smallCode: 'VA',
    country: 'Vatican City State',
    nationality: 'Vatican',
  },
  'HND;Honduran;': {
    code: 'HND',
    smallCode: 'HN',
    country: 'Honduras',
    nationality: 'Honduran',
  },
  'HKG;Hong Kong;': {
    code: 'HKG',
    smallCode: 'HK',
    country: 'Hong Kong',
    nationality: 'Hong Kong',
  },
  'HUN;Hungarian;': {
    code: 'HUN',
    smallCode: 'HU',
    country: 'Hungary',
    nationality: 'Hungarian',
  },
  'ISL;Icelandic;': {
    code: 'ISL',
    smallCode: 'IS',
    country: 'Iceland',
    nationality: 'Icelandic',
  },
  'IND;Indian;': {
    code: 'IND',
    smallCode: 'IN',
    country: 'India',
    nationality: 'Indian',
  },
  'IDN;Indonesian;': {
    code: 'IDN',
    smallCode: 'ID',
    country: 'Indonesia',
    nationality: 'Indonesian',
  },
  'IRN;Iranian;': {
    code: 'IRN',
    smallCode: 'IR',
    country: 'Iran',
    nationality: 'Iranian',
  },
  'IRQ;Iraqi;': {
    code: 'IRQ',
    smallCode: 'IQ',
    country: 'Iraq',
    nationality: 'Iraqi',
  },
  'IRL;Irish;': {
    code: 'IRL',
    smallCode: 'IE',
    country: 'Ireland',
    nationality: 'Irish',
  },
  'IMN;Manx;': {
    code: 'IMN',
    smallCode: 'IM',
    country: 'Isle of Man',
    nationality: 'Manx',
  },
  'ISR;Israeli;': {
    code: 'ISR',
    smallCode: 'IL',
    country: 'Israel',
    nationality: 'Israeli',
  },
  'ITA;Italian;': {
    code: 'ITA',
    smallCode: 'IT',
    country: 'Italy',
    nationality: 'Italian',
  },
  'JAM;Jamaican;': {
    code: 'JAM',
    smallCode: 'JM',
    country: 'Jamaica',
    nationality: 'Jamaican',
  },
  'JPN;Japanese;': {
    code: 'JPN',
    smallCode: 'JP',
    country: 'Japan',
    nationality: 'Japanese',
  },
  'JEY;Channel Island;': {
    code: 'JEY',
    smallCode: 'JE',
    country: 'Jersey',
    nationality: 'Channel Island',
  },
  'JOR;Jordanian;': {
    code: 'JOR',
    smallCode: 'JO',
    country: 'Jordan',
    nationality: 'Jordanian',
  },
  'KAZ;Kazakhstani;': {
    code: 'KAZ',
    smallCode: 'KZ',
    country: 'Kazakhstan',
    nationality: 'Kazakhstani',
  },
  'KEN;Kenyan;': {
    code: 'KEN',
    smallCode: 'KE',
    country: 'Kenya',
    nationality: 'Kenyan',
  },
  'KIR;I-Kiribati;': {
    code: 'KIR',
    smallCode: 'KI',
    country: 'Kiribati',
    nationality: 'I-Kiribati',
  },
  'PRK;North Korean;': {
    code: 'PRK',
    smallCode: 'KP',
    country: "Korea (Democratic People's Republic of)",
    nationality: 'North Korean',
  },
  'KOR;South Korean;': {
    code: 'KOR',
    smallCode: 'KR',
    country: 'Korea (Republic of)',
    nationality: 'South Korean',
  },
  'KWT;Kuwaiti;': {
    code: 'KWT',
    smallCode: 'KW',
    country: 'Kuwait',
    nationality: 'Kuwaiti',
  },
  'KGZ;Kyrgyzstani;': {
    code: 'KGZ',
    smallCode: 'KG',
    country: 'Kyrgyzstan',
    nationality: 'Kyrgyzstani',
  },
  'LAO;Lao;': {
    code: 'LAO',
    smallCode: 'LA',
    country: "Lao People's Democratic Republic",
    nationality: 'Lao',
  },
  'LVA;Latvian;': {
    code: 'LVA',
    smallCode: 'LV',
    country: 'Latvia',
    nationality: 'Latvian',
  },
  'LBN;Lebanese;': {
    code: 'LBN',
    smallCode: 'LB',
    country: 'Lebanon',
    nationality: 'Lebanese',
  },
  'LSO;Basotho;': {
    code: 'LSO',
    smallCode: 'LS',
    country: 'Lesotho',
    nationality: 'Basotho',
  },
  'LBR;Liberian;': {
    code: 'LBR',
    smallCode: 'LR',
    country: 'Liberia',
    nationality: 'Liberian',
  },
  'LBY;Libyan;': {
    code: 'LBY',
    smallCode: 'LY',
    country: 'Libya',
    nationality: 'Libyan',
  },
  'LIE;Liechtenstein;': {
    code: 'LIE',
    smallCode: 'LI',
    country: 'Liechtenstein',
    nationality: 'Liechtenstein',
  },
  'LTU;Lithuanian;': {
    code: 'LTU',
    smallCode: 'LT',
    country: 'Lithuania',
    nationality: 'Lithuanian',
  },
  'LUX;Luxembourg;': {
    code: 'LUX',
    smallCode: 'LU',
    country: 'Luxembourg',
    nationality: 'Luxembourg',
  },
  'MAC;Macanese;': {
    code: 'MAC',
    smallCode: 'MO',
    country: 'Macao',
    nationality: 'Macanese',
  },
  'MKD;Macedonian;': {
    code: 'MKD',
    smallCode: 'MK',
    country: 'Macedonia (the former Yugoslav Republic of)',
    nationality: 'Macedonian',
  },
  'MDG;Malagasy;': {
    code: 'MDG',
    smallCode: 'MG',
    country: 'Madagascar',
    nationality: 'Malagasy',
  },
  'MWI;Malawian;': {
    code: 'MWI',
    smallCode: 'MW',
    country: 'Malawi',
    nationality: 'Malawian',
  },
  'MYS;Malaysian;': {
    code: 'MYS',
    smallCode: 'MY',
    country: 'Malaysia',
    nationality: 'Malaysian',
  },
  'MDV;Maldivian;': {
    code: 'MDV',
    smallCode: 'MV',
    country: 'Maldives',
    nationality: 'Maldivian',
  },
  'MLI;Malian;': {
    code: 'MLI',
    smallCode: 'ML',
    country: 'Mali',
    nationality: 'Malian',
  },
  'MLT;Maltese;': {
    code: 'MLT',
    smallCode: 'MT',
    country: 'Malta',
    nationality: 'Maltese',
  },
  'MHL;Marshallese;': {
    code: 'MHL',
    smallCode: 'MH',
    country: 'Marshall Islands',
    nationality: 'Marshallese',
  },
  'MTQ;Martiniquais;': {
    code: 'MTQ',
    smallCode: 'MQ',
    country: 'Martinique',
    nationality: 'Martiniquais',
  },
  'MRT;Mauritanian;': {
    code: 'MRT',
    smallCode: 'MR',
    country: 'Mauritania',
    nationality: 'Mauritanian',
  },
  'MUS;Mauritian;': {
    code: 'MUS',
    smallCode: 'MU',
    country: 'Mauritius',
    nationality: 'Mauritian',
  },
  'MYT;Mahoran;': {
    code: 'MYT',
    smallCode: 'YT',
    country: 'Mayotte',
    nationality: 'Mahoran',
  },
  'MEX;Mexican;': {
    code: 'MEX',
    smallCode: 'MX',
    country: 'Mexico',
    nationality: 'Mexican',
  },
  'FSM;Micronesian;': {
    code: 'FSM',
    smallCode: 'FM',
    country: 'Micronesia (Federated States of)',
    nationality: 'Micronesian',
  },
  'MDA;Moldovan;': {
    code: 'MDA',
    smallCode: 'MD',
    country: 'Moldova (Republic of)',
    nationality: 'Moldovan',
  },
  'MCO;Mon\u00e9gasque;': {
    code: 'MCO',
    smallCode: 'MC',
    country: 'Monaco',
    nationality: 'Mon\u00e9gasque',
  },
  'MNG;Mongolian;': {
    code: 'MNG',
    smallCode: 'MN',
    country: 'Mongolia',
    nationality: 'Mongolian',
  },
  'MNE;Montenegrin;': {
    code: 'MNE',
    smallCode: 'ME',
    country: 'Montenegro',
    nationality: 'Montenegrin',
  },
  'MSR;Montserratian;': {
    code: 'MSR',
    smallCode: 'MS',
    country: 'Montserrat',
    nationality: 'Montserratian',
  },
  'MAR;Moroccan;': {
    code: 'MAR',
    smallCode: 'MA',
    country: 'Morocco',
    nationality: 'Moroccan',
  },
  'MOZ;Mozambican;': {
    code: 'MOZ',
    smallCode: 'MZ',
    country: 'Mozambique',
    nationality: 'Mozambican',
  },
  'MMR;Burmese;': {
    code: 'MMR',
    smallCode: 'MM',
    country: 'Myanmar',
    nationality: 'Burmese',
  },
  'NAM;Namibian;': {
    code: 'NAM',
    smallCode: 'NA',
    country: 'Namibia',
    nationality: 'Namibian',
  },
  'NRU;Nauruan;': {
    code: 'NRU',
    smallCode: 'NR',
    country: 'Nauru',
    nationality: 'Nauruan',
  },
  'NPL;Nepali;': {
    code: 'NPL',
    smallCode: 'NP',
    country: 'Nepal',
    nationality: 'Nepali',
  },
  'NLD;Dutch;': {
    code: 'NLD',
    smallCode: 'NL',
    country: 'Netherlands',
    nationality: 'Dutch',
  },
  'NCL;New Caledonian;': {
    code: 'NCL',
    smallCode: 'NC',
    country: 'New Caledonia',
    nationality: 'New Caledonian',
  },
  'NZL;New Zealand;': {
    code: 'NZL',
    smallCode: 'NZ',
    country: 'New Zealand',
    nationality: 'New Zealand',
  },
  'NIC;Nicaraguan;': {
    code: 'NIC',
    smallCode: 'NI',
    country: 'Nicaragua',
    nationality: 'Nicaraguan',
  },
  'NER;Nigerien;': {
    code: 'NER',
    smallCode: 'NE',
    country: 'Niger',
    nationality: 'Nigerien',
  },
  'NGA;Nigerian;': {
    code: 'NGA',
    smallCode: 'NG',
    country: 'Nigeria',
    nationality: 'Nigerian',
  },
  'NIU;Niuean;': {
    code: 'NIU',
    smallCode: 'NU',
    country: 'Niue',
    nationality: 'Niuean',
  },
  'NFK;Norfolk Island;': {
    code: 'NFK',
    smallCode: 'NF',
    country: 'Norfolk Island',
    nationality: 'Norfolk Island',
  },
  'MNP;Northern Marianan;': {
    code: 'MNP',
    smallCode: 'MP',
    country: 'Northern Mariana Islands',
    nationality: 'Northern Marianan',
  },
  'NOR;Norwegian;': {
    code: 'NOR',
    smallCode: 'NO',
    country: 'Norway',
    nationality: 'Norwegian',
  },
  'OMN;Omani;': {
    code: 'OMN',
    smallCode: 'OM',
    country: 'Oman',
    nationality: 'Omani',
  },
  'PAK;Pakistani;': {
    code: 'PAK',
    smallCode: 'PK',
    country: 'Pakistan',
    nationality: 'Pakistani',
  },
  'PLW;Palauan;': {
    code: 'PLW',
    smallCode: 'PW',
    country: 'Palau',
    nationality: 'Palauan',
  },
  'PSE;Palestinian;': {
    code: 'PSE',
    smallCode: 'PS',
    country: 'Palestine',
    nationality: 'Palestinian',
  },
  'PAN;Panamanian;': {
    code: 'PAN',
    smallCode: 'PA',
    country: 'Panama',
    nationality: 'Panamanian',
  },
  'PNG;Papua New Guinean;': {
    code: 'PNG',
    smallCode: 'PG',
    country: 'Papua New Guinea',
    nationality: 'Papua New Guinean',
  },
  'PRY;Paraguayan;': {
    code: 'PRY',
    smallCode: 'PY',
    country: 'Paraguay',
    nationality: 'Paraguayan',
  },
  'PER;Peruvian;': {
    code: 'PER',
    smallCode: 'PE',
    country: 'Peru',
    nationality: 'Peruvian',
  },
  'PHL;Philippine;': {
    code: 'PHL',
    smallCode: 'PH',
    country: 'Philippines',
    nationality: 'Philippine',
  },
  'PCN;Pitcairn Island;': {
    code: 'PCN',
    smallCode: 'PN',
    country: 'Pitcairn',
    nationality: 'Pitcairn Island',
  },
  'POL;Polish;': {
    code: 'POL',
    smallCode: 'PL',
    country: 'Poland',
    nationality: 'Polish',
  },
  'PRT;Portuguese;': {
    code: 'PRT',
    smallCode: 'PT',
    country: 'Portugal',
    nationality: 'Portuguese',
  },
  'PRI;Puerto Rican;': {
    code: 'PRI',
    smallCode: 'PR',
    country: 'Puerto Rico',
    nationality: 'Puerto Rican',
  },
  'QAT;Qatari;': {
    code: 'QAT',
    smallCode: 'QA',
    country: 'Qatar',
    nationality: 'Qatari',
  },
  'REU;R\u00e9unionese;': {
    code: 'REU',
    smallCode: 'RE',
    country: 'R\u00e9union',
    nationality: 'R\u00e9unionese',
  },
  'ROU;Romanian;': {
    code: 'ROU',
    smallCode: 'RO',
    country: 'Romania',
    nationality: 'Romanian',
  },
  'RUS;Russian;': {
    code: 'RUS',
    smallCode: 'RU',
    country: 'Russian Federation',
    nationality: 'Russian',
  },
  'RWA;Rwandan;': {
    code: 'RWA',
    smallCode: 'RW',
    country: 'Rwanda',
    nationality: 'Rwandan',
  },
  'BLM;Barth\u00e9lemois;': {
    code: 'BLM',
    smallCode: 'BL',
    country: 'Saint Barth\u00e9lemy',
    nationality: 'Barth\u00e9lemois',
  },
  'SHN;Saint Helenian;': {
    code: 'SHN',
    smallCode: 'SH',
    country: 'Saint Helena',
    nationality: 'Saint Helenian',
  },
  'KNA;Kittitian or Nevisian;': {
    code: 'KNA',
    smallCode: 'KN',
    country: 'Saint Kitts and Nevis',
    nationality: 'Kittitian or Nevisian',
  },
  'LCA;Saint Lucian;': {
    code: 'LCA',
    smallCode: 'LC',
    country: 'Saint Lucia',
    nationality: 'Saint Lucian',
  },
  'MAF;Saint-Martinoise;': {
    code: 'MAF',
    smallCode: 'MF',
    country: 'Saint Martin (French part)',
    nationality: 'Saint-Martinoise',
  },
  'SPM;Saint-Pierrais or Miquelonnais;': {
    code: 'SPM',
    smallCode: 'PM',
    country: 'Saint Pierre and Miquelon',
    nationality: 'Saint-Pierrais or Miquelonnais',
  },
  'VCT;Saint Vincentian;': {
    code: 'VCT',
    smallCode: 'VC',
    country: 'Saint Vincent and the Grenadines',
    nationality: 'Saint Vincentian',
  },
  'WSM;Samoan;': {
    code: 'WSM',
    smallCode: 'WS',
    country: 'Samoa',
    nationality: 'Samoan',
  },
  'SMR;Sammarinese;': {
    code: 'SMR',
    smallCode: 'SM',
    country: 'San Marino',
    nationality: 'Sammarinese',
  },
  'STP;S\u00e3o Tom\u00e9an;': {
    code: 'STP',
    smallCode: 'ST',
    country: 'Sao Tome and Principe',
    nationality: 'S\u00e3o Tom\u00e9an',
  },
  'SAU;Saudi;': {
    code: 'SAU',
    smallCode: 'SA',
    country: 'Saudi Arabia',
    nationality: 'Saudi',
  },
  'SEN;Senegalese;': {
    code: 'SEN',
    smallCode: 'SN',
    country: 'Senegal',
    nationality: 'Senegalese',
  },
  'SRB;Serbian;': {
    code: 'SRB',
    smallCode: 'RS',
    country: 'Serbia',
    nationality: 'Serbian',
  },
  'SYC;Seychellois;': {
    code: 'SYC',
    smallCode: 'SC',
    country: 'Seychelles',
    nationality: 'Seychellois',
  },
  'SLE;Sierra Leonean;': {
    code: 'SLE',
    smallCode: 'SL',
    country: 'Sierra Leone',
    nationality: 'Sierra Leonean',
  },
  'SGP;Singaporean;': {
    code: 'SGP',
    smallCode: 'SG',
    country: 'Singapore',
    nationality: 'Singaporean',
  },
  'SXM;Sint Maarten;': {
    code: 'SXM',
    smallCode: 'SX',
    country: 'Sint Maarten (Dutch part)',
    nationality: 'Sint Maarten',
  },
  'SVK;Slovak;': {
    code: 'SVK',
    smallCode: 'SK',
    country: 'Slovakia',
    nationality: 'Slovak',
  },
  'SVN;Slovenian;': {
    code: 'SVN',
    smallCode: 'SI',
    country: 'Slovenia',
    nationality: 'Slovenian',
  },
  'SLB;Solomon Island;': {
    code: 'SLB',
    smallCode: 'SB',
    country: 'Solomon Islands',
    nationality: 'Solomon Island',
  },
  'SOM;Somali;': {
    code: 'SOM',
    smallCode: 'SO',
    country: 'Somalia',
    nationality: 'Somali',
  },
  'ZAF;South African;': {
    code: 'ZAF',
    smallCode: 'ZA',
    country: 'South Africa',
    nationality: 'South African',
  },
  'SGS;South Georgia or South Sandwich Islands;': {
    code: 'SGS',
    smallCode: 'GS',
    country: 'South Georgia and the South Sandwich Islands',
    nationality: 'South Georgia or South Sandwich Islands',
  },
  'SSD;South Sudanese;': {
    code: 'SSD',
    smallCode: 'SS',
    country: 'South Sudan',
    nationality: 'South Sudanese',
  },
  'ESP;Spanish;': {
    code: 'ESP',
    smallCode: 'ES',
    country: 'Spain',
    nationality: 'Spanish',
  },
  'LKA;Sri Lankan;': {
    code: 'LKA',
    smallCode: 'LK',
    country: 'Sri Lanka',
    nationality: 'Sri Lankan',
  },
  'SDN;Sudanese;': {
    code: 'SDN',
    smallCode: 'SD',
    country: 'Sudan',
    nationality: 'Sudanese',
  },
  'SUR;Surinamese;': {
    code: 'SUR',
    smallCode: 'SR',
    country: 'Suriname',
    nationality: 'Surinamese',
  },
  'SJM;Svalbard;': {
    code: 'SJM',
    smallCode: 'SJ',
    country: 'Svalbard and Jan Mayen',
    nationality: 'Svalbard',
  },
  'SWZ;Swazi;': {
    code: 'SWZ',
    smallCode: 'SZ',
    country: 'Swaziland',
    nationality: 'Swazi',
  },
  'SWE;Swedish;': {
    code: 'SWE',
    smallCode: 'SE',
    country: 'Sweden',
    nationality: 'Swedish',
  },
  'CHE;Swiss;': {
    code: 'CHE',
    smallCode: 'CH',
    country: 'Switzerland',
    nationality: 'Swiss',
  },
  'SYR;Syrian;': {
    code: 'SYR',
    smallCode: 'SY',
    country: 'Syrian Arab Republic',
    nationality: 'Syrian',
  },
  'TWN;Chinese;': {
    code: 'TWN',
    smallCode: 'TW',
    country: 'Taiwan',
    nationality: 'Chinese',
  },
  'TJK;Tajikistani;': {
    code: 'TJK',
    smallCode: 'TJ',
    country: 'Tajikistan',
    nationality: 'Tajikistani',
  },
  'TZA;Tanzanian;': {
    code: 'TZA',
    smallCode: 'TZ',
    country: 'Tanzania',
    nationality: 'Tanzanian',
  },
  'THA;Thai;': {
    code: 'THA',
    smallCode: 'TH',
    country: 'Thailand',
    nationality: 'Thai',
  },
  'TLS;Timorese;': {
    code: 'TLS',
    smallCode: 'TL',
    country: 'Timor-Leste',
    nationality: 'Timorese',
  },
  'TGO;Togolese;': {
    code: 'TGO',
    smallCode: 'TG',
    country: 'Togo',
    nationality: 'Togolese',
  },
  'TKL;Tokelauan;': {
    code: 'TKL',
    smallCode: 'TK',
    country: 'Tokelau',
    nationality: 'Tokelauan',
  },
  'TON;Tongan;': {
    code: 'TON',
    smallCode: 'TO',
    country: 'Tonga',
    nationality: 'Tongan',
  },
  'TTO;Trinidadian or Tobagonian;': {
    code: 'TTO',
    smallCode: 'TT',
    country: 'Trinidad and Tobago',
    nationality: 'Trinidadian or Tobagonian',
  },
  'TUN;Tunisian;': {
    code: 'TUN',
    smallCode: 'TN',
    country: 'Tunisia',
    nationality: 'Tunisian',
  },
  'TUR;Turkish;': {
    code: 'TUR',
    smallCode: 'TR',
    country: 'Turkey',
    nationality: 'Turkish',
  },
  'TKM;Turkmen;': {
    code: 'TKM',
    smallCode: 'TM',
    country: 'Turkmenistan',
    nationality: 'Turkmen',
  },
  'TCA;Turks and Caicos Island;': {
    code: 'TCA',
    smallCode: 'TC',
    country: 'Turks and Caicos Islands',
    nationality: 'Turks and Caicos Island',
  },
  'TUV;Tuvaluan;': {
    code: 'TUV',
    smallCode: 'TV',
    country: 'Tuvalu',
    nationality: 'Tuvaluan',
  },
  'UGA;Ugandan;': {
    code: 'UGA',
    smallCode: 'UG',
    country: 'Uganda',
    nationality: 'Ugandan',
  },
  'UKR;Ukrainian;': {
    code: 'UKR',
    smallCode: 'UA',
    country: 'Ukraine',
    nationality: 'Ukrainian',
  },
  'ARE;Emirati;': {
    code: 'ARE',
    smallCode: 'AE',
    country: 'United Arab Emirates',
    nationality: 'Emirati',
  },
  'GBR;British;': {
    code: 'GBR',
    smallCode: 'GB',
    country: 'United Kingdom of Great Britain and Northern Ireland',
    nationality: 'British',
  },
  'USA;American;': {
    code: 'USA',
    smallCode: 'US',
    country: 'United States of America',
    nationality: 'American',
  },
  'UMI;American;': {
    code: 'UMI',
    smallCode: 'UM',
    country: 'United States Minor Outlying Islands',
    nationality: 'American',
  },
  'URY;Uruguayan;': {
    code: 'URY',
    smallCode: 'UY',
    country: 'Uruguay',
    nationality: 'Uruguayan',
  },
  'UZB;Uzbekistani;': {
    code: 'UZB',
    smallCode: 'UZ',
    country: 'Uzbekistan',
    nationality: 'Uzbekistani',
  },
  'VUT;Ni-Vanuatu;': {
    code: 'VUT',
    smallCode: 'VU',
    country: 'Vanuatu',
    nationality: 'Ni-Vanuatu',
  },
  'VEN;Venezuelan;': {
    code: 'VEN',
    smallCode: 'VE',
    country: 'Venezuela (Bolivarian Republic of)',
    nationality: 'Venezuelan',
  },
  'VNM;Vietnamese;': {
    code: 'VNM',
    smallCode: 'VN',
    country: 'Vietnam',
    nationality: 'Vietnamese',
  },
  'VGB;British Virgin Island;': {
    code: 'VGB',
    smallCode: 'VG',
    country: 'Virgin Islands (British)',
    nationality: 'British Virgin Island',
  },
  'VIR;U.S. Virgin Island;': {
    code: 'VIR',
    smallCode: 'VI',
    country: 'Virgin Islands (U.S.)',
    nationality: 'U.S. Virgin Island',
  },
  'WLF;Wallis and Futuna;': {
    code: 'WLF',
    smallCode: 'WF',
    country: 'Wallis and Futuna',
    nationality: 'Wallis and Futuna',
  },
  'ESH;Sahrawi;': {
    code: 'ESH',
    smallCode: 'EH',
    country: 'Western Sahara',
    nationality: 'Sahrawi',
  },
  'YEM;Yemeni;': {
    code: 'YEM',
    smallCode: 'YE',
    country: 'Yemen',
    nationality: 'Yemeni',
  },
  'ZMB;Zambian;': {
    code: 'ZMB',
    smallCode: 'ZM',
    country: 'Zambia',
    nationality: 'Zambian',
  },
  'ZWE;Zimbabwean;': {
    code: 'ZWE',
    smallCode: 'ZW',
    country: 'Zimbabwe',
    nationality: 'Zimbabwean',
  },
};

const getNationality = (part = '') => {
  const formatted = `${part};`;

  const key = Object.keys(nationlities).find((nationality) =>
    nationality.includes(formatted),
  );

  return nationlities[key];
};

const getFlag = (part = '') => {
  const code = (getNationality(part)?.smallCode ?? 'br').toLowerCase();

  return `https://hatscripts.github.io/circle-flags/flags/${code}.svg`;
};

export { getNationality, getFlag };
export default nationlities;
